version: '3.1'
services:
  database-service:
    image: postgres
    restart: always
    ports:
      - 55432:5432 
    volumes:
      - D:\\pgvolume\:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pg@123
      POSTGRES_USER: pg
    